language: ruby
sudo: false
rvm:
  - 1.9
  - 2.0.0
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.0
before_install:
  - gem update bundler
before_script:
  - npm install jsonlint
script: "bundle exec rake && $(npm bin)/jsonlint app.json"
notifications:
  email:
    - ogataken@gmail.com
branches:
  only:
    - master
